#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("cec.Resource", IsApplication=true)]

namespace cec
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int resultArray = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int csharp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int waterfront = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int xaml = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int Check = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int algo = 2131099650;
			
			// aapt resource value: 0x7f06000a
			public const int btcLabel = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int btcText = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int btcsec = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int gpu = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int spinner1 = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int spinner2 = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int spinner3 = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int usdText = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int usdlabel = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int usdsec = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int typeResult = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
